# Generated by Django 4.1.7 on 2023-07-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indu', '0002_coffy_remove_momo_info_delete_info_delete_momo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffy',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
