# Generated by Django 4.1.7 on 2023-07-26 07:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indu', '0005_cont'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cont',
        ),
        migrations.DeleteModel(
            name='Tea',
        ),
        migrations.AddField(
            model_name='coffy',
            name='summary',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
