# Generated by Django 4.1.7 on 2023-07-26 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indu', '0007_coffee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='title',
        ),
    ]
